name: 'Build Affected'
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout branch'
        uses: actions/checkout@v3
      - name: 'Use Node 18'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Install dependencies'
        run: 'npm ci'
      - name: 'Build projects'
        run: 'npx nx affected --target=build'
