name: npm Package

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'packages/**'
      - 'package*.json'
      - 'tsconfig.base.json'
      - 'babel.config.json'
      - 'nx.json'
      - 'workspace.json'

jobs:
  version:
    name: Check Version
    uses: imyourmanzi/GitHubWorkflows/.github/workflows/npm-check-version.skip.yml@main
