name: 'Check Version'

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'packages/**'
      - 'package*.json'
      - 'tsconfig.base.json'
      - 'babel.config.json'
      - 'nx.json'
      - 'workspace.json'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No version bump required"'
