name: 'Check Version'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'package*.json'
      - 'tsconfig.base.json'
      - 'babel.config.json'
      - 'nx.json'
      - 'workspace.json'

jobs:
  npm:
    name: 'npm Package'
    uses: imyourmanzi/GitHubWorkflows/.github/workflows/check-version-npm.yml@main
